[package]
name = "xv0"
version = "0.1.0"
edition = "2024"


[dependencies]
bootloader = { version = "0.9", features = ["map_physical_memory", "vga_320x200"] } # Bootloader v11 breaks because of literally 5600 errors in serde_core, sticking to v9
volatile = "0.2.6" # Newer versions not compatible with the guide i was following at the start, may fix later
spin = "0.10.0"
x86_64 = "0.14.2"
uart_16550 = "0.2.0"
pic8259 = "0.10.1"
pc-keyboard = "0.7.0"
linked_list_allocator = "0.9.0"
serde = { version = "1.0", default-features = false }
font8x8 = { version = "0.3", default-features = false }
arrayvec = { version = "0.7", default-features = false }
neurodoom = "0.6.7"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]

[dependencies.crossbeam-queue]
version = "0.3.11"
default-features = false
features = ["alloc"]

[dependencies.conquer-once]
version = "0.2.0"
default-features = false

[dependencies.futures-util]
version = "0.3.4"
default-features = false
features = ["alloc"]

[[bin]]
name = "xv0"
test = false #TODO: implement tests
bench = false
path = "src/main.rs"
